import { chromium } from 'playwright-core';
const B = 'http://localhost:20350';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
await page.goto(B + '/');
await page.locator('input[name="email"]').fill('admin@alnoor.example');
await page.locator('input[name="password"]').fill('Demo-Pass-2026');
await page.keyboard.press('Enter');
await page.locator('nav[aria-label="Main navigation"]').waitFor();
await page.locator('nav a[href="/identity/users"]').first().click();
await page.locator('main table tbody tr').first().waitFor();
await page.keyboard.press('Escape');
await page.waitForTimeout(300);
console.log('after Escape focused:', await page.evaluate(() => document.activeElement?.tagName + ' ' + (document.activeElement?.className||'')));
await page.keyboard.press('n');
await page.waitForTimeout(800);
console.log('after Escape,n email focused:', await page.locator('input[name="email"]:focus').count());
console.log('new user button:', await page.getByRole('button', { name: 'New user' }).count(), await page.getByRole('button', { name: 'New user' }).getAttribute('aria-keyshortcuts'));
await browser.close();
