import { chromium } from 'playwright-core';
const B = 'http://localhost:20350';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } }); const page = await ctx.newPage();
await page.goto(B + '/'); await page.locator('input[name="email"]').fill('admin@alnoor.example'); await page.locator('input[name="password"]').fill('Demo-Pass-2026'); await page.keyboard.press('Enter');
await page.locator('nav[aria-label]').first().waitFor();
const H = { 'X-Erp-Request': '1' };
const email = `critic.deact.${Date.now() % 100000}@alnoor.example`;
const u = await (await page.request.post(B + '/api/identity/users', { headers: H, data: { email, displayName: 'Critic Deact', language: 'en', password: 'Critic-Pass-2026x', mustChangePassword: false, roleIds: [] } })).json();
await page.goto(B + `/identity/users?open=${u.id}`);
await page.locator('aside h2').waitFor();
const box = page.locator('aside label.id-check input[type=checkbox]');
console.log('active checkbox before:', await box.isChecked());
await box.focus(); await page.keyboard.press('Space');
console.log('after Space:', await box.isChecked());
await page.keyboard.press('Control+Enter');
await page.waitForTimeout(1000);
console.log('notice:', await page.locator('aside [role=status], aside [role=alert]').allInnerTexts());
const after = await (await page.request.get(B + `/api/identity/users/${u.id}`)).json();
console.log('isActive via API after keyboard save:', after.isActive);
const r = await (await browser.newContext()).request.post(B + '/api/auth/sign-in', { headers: H, data: { email, password: 'Critic-Pass-2026x' } });
console.log('sign-in after deactivation:', r.status());
await browser.close();
