import { createRequire } from 'node:module';
const require = createRequire('/home/user/critic/p04-shell-r2/gauntlet/compare/package.json');
const { chromium } = require('playwright-core');
const base = 'http://localhost:20450';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await (await b.newContext({ viewport: { width: 1366, height: 820 } })).newPage();
await page.goto(base + '/');
await page.fill('input[name=email]', 'admin@alnoor.example'); await page.fill('input[name=password]', 'Demo-Pass-2026'); await page.keyboard.press('Enter');
await page.locator('nav.navpane').waitFor(); await page.waitForTimeout(500);
const st = async (l) => console.log(l, JSON.stringify(await page.evaluate(() => { const g = document.querySelector('main table[role=grid]'); const id = g?.getAttribute('aria-activedescendant'); return { url: location.pathname + location.search, focus: document.activeElement?.tagName + '.' + (document.activeElement?.className||''), active: id ? document.getElementById(id)?.textContent?.slice(0, 50) : null }; })));
await page.keyboard.press('Alt+m'); await page.waitForTimeout(200); await page.keyboard.press('Enter');
await page.locator('main table tbody tr').first().waitFor(); await page.waitForTimeout(300);
await st('landed');
await page.keyboard.press('ArrowDown'); await page.waitForTimeout(200); await st('down1');
await page.keyboard.press('ArrowDown'); await page.waitForTimeout(200); await st('down2');
await page.keyboard.press('ArrowDown'); await page.waitForTimeout(200); await st('down3');
console.log('rows', JSON.stringify(await page.evaluate(() => [...document.querySelectorAll('main table tbody tr')].slice(0, 3).map(r => r.textContent.slice(0, 40)))));
await page.keyboard.press('Enter'); await page.waitForTimeout(800); await st('enter');
console.log('panel', await page.evaluate(() => document.querySelector('main [role=dialog], main aside, .user-panel')?.textContent?.slice(0, 120)));
await b.close();
