import { signIn } from './lib.mjs';
const log = (...a) => console.log(...a);
const A = await signIn('admin@alnoor.example');
const roles = (await A.get('/api/identity/roles?take=50')).json.items;
const adminRole = roles.find(r => /admin/i.test(r.nameEn ?? r.name ?? r.code ?? JSON.stringify(r)));
log('role', JSON.stringify(adminRole).slice(0, 200));
const companies = (await A.get('/api/tenancy/companies?take=50')).json.items;
const dxb = companies.find(c => c.code === 'ALN-DXB'), shj = companies.find(c => c.code === 'ALN-SHJ');
const dxbBranches = (await A.get(`/api/tenancy/branches?filter=${encodeURIComponent(`companyId eq '${dxb.id}'`)}`)).json.items;
log('DXB branches', dxbBranches.map(b => b.code));
const stamp = Date.now().toString(36);
async function mkUser(email, access) {
  const r = await A.post('/api/identity/users', { email, displayName: 'Critic ' + email.split('@')[0], displayNameAr: 'ناقد', language: 'en', password: 'Critic-Pass-2026!x', roleIds: [adminRole.id], mustChangePassword: false });
  if (r.status >= 300) throw new Error('create user ' + r.status + r.text);
  const id = r.json.id ?? r.json.user?.id;
  const cur = (await A.get('/api/tenancy/access/' + id)).json;
  const u = await A.put('/api/tenancy/access/' + id, { companies: access, version: cur.version });
  log('access set', email, u.status, u.text.slice(0, 150));
  return id;
}
const shjEmail = `c6-shj-${stamp}@alnoor.example`, brEmail = `c6-br-${stamp}@alnoor.example`;
await mkUser(shjEmail, [{ companyId: shj.id, allBranches: true }]);
const br1 = dxbBranches[0], br2 = dxbBranches[1];
await mkUser(brEmail, [{ companyId: dxb.id, allBranches: false, branchIds: [br1.id] }]);
const S = await signIn(shjEmail, 'Critic-Pass-2026!x');
const R = await signIn(brEmail, 'Critic-Pass-2026!x');
log('--- company-limited (SHJ only) admin');
log('companies list', (await S.get('/api/tenancy/companies')).json.items.map(c => c.code));
log('GET DXB', (await S.get('/api/tenancy/companies/' + dxb.id)).status);
log('GET DXB branch', (await S.get('/api/tenancy/branches/' + br1.id)).status);
log('report profile DXB', (await S.get(`/api/reports/run/tenancy.companyProfile?company=${dxb.id}&format=json`)).status);
const bd = await S.get(`/api/reports/run/tenancy.branchDirectory?format=csv&includeInactive=true`);
log('branch directory csv includes DXB?', bd.status, bd.text.includes('ALN-DXB'), bd.text.split('\n').length);
const t = (await S.get('/api/tenancy/tenant'));
log('GET tenant', t.status);
const tput = await S.put('/api/tenancy/tenant', { ...t.json, nameEn: t.json.nameEn + ' (renamed by SHJ admin)' });
log('PUT tenant as SHJ-only admin', tput.status, tput.text.slice(0, 200));
if (tput.status === 200) { const back = await A.get('/api/tenancy/tenant'); await A.put('/api/tenancy/tenant', { ...back.json, nameEn: t.json.nameEn }); }
log('POST company as SHJ-only', (await S.post('/api/tenancy/companies', { legalNameEn: 'Sneaky', legalNameAr: 'x', baseCurrency: 'AED', fiscalYearStartMonth: 1, fiscalYearStartDay: 1, country: 'AE', isActive: true })).status);
const adminSelf = (await A.get('/api/identity/users?search=admin%40alnoor')).json.items.find(u => u.email === 'admin@alnoor.example');
const aa = (await S.get('/api/tenancy/access/' + adminSelf.id)).json;
log('access of tenant admin as seen by SHJ admin', JSON.stringify({ canEdit: aa.canEdit, reason: aa.readOnlyReason, companies: aa.companies?.length }));
log('PUT access remove admin from SHJ', (await S.put('/api/tenancy/access/' + adminSelf.id, { companies: [], version: aa.version })).status);
log('workplace switch to DXB', (await S.put('/api/tenancy/workplace', { companyId: dxb.id })).status);
log('--- branch-limited admin (DXB, one branch ' + br1.code + ')');
log('branches list', (await R.get('/api/tenancy/branches')).json.items.map(b => b.code));
log('GET other branch', (await R.get('/api/tenancy/branches/' + br2.id)).status);
const dfull = (await R.get('/api/tenancy/companies/' + dxb.id)).json;
log('company everyBranch', dfull.everyBranch);
log('PUT company (rename)', (await R.put('/api/tenancy/companies/' + dxb.id, { ...dfull, legalNameEn: dfull.legalNameEn + ' X' })).text.slice(0, 160));
log('PUT company (deactivate)', (await R.put('/api/tenancy/companies/' + dxb.id, { ...dfull, isActive: false })).status);
log('PUT logo', (await R.put('/api/tenancy/companies/' + dxb.id + '/logo', { contentType: 'image/png', data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==' })).status);
log('DELETE logo', (await R.del('/api/tenancy/companies/' + dxb.id + '/logo')).status);
log('POST branch', (await R.post('/api/tenancy/branches', { companyId: dxb.id, nameEn: 'Sneaky branch', nameAr: 'x', country: 'AE', isActive: true })).status);
const b1 = (await R.get('/api/tenancy/branches/' + br1.id)).json;
log('PUT own branch code change', (await R.put('/api/tenancy/branches/' + br1.id, { ...b1, code: b1.code + 'X' })).status);
log('PUT other branch', (await R.put('/api/tenancy/branches/' + br2.id, { ...b1, id: br2.id, nameEn: 'pwn' })).status);
log('workplace switch other branch', (await R.put('/api/tenancy/workplace', { companyId: dxb.id, branchId: br2.id })).status);
const bdr = await R.get(`/api/reports/run/tenancy.branchDirectory?format=csv&company=${dxb.id}&includeInactive=true`);
log('branch directory as branch-limited: other branch present?', bdr.text.includes(br2.code), bdr.text.trim().split('\n').length - 1, 'rows');
const ac = await R.get('/api/tenancy/access?take=200');
log('access list status', ac.status, 'rows', ac.json?.items?.length);
const viewer = (await A.get('/api/identity/users?search=viewer')).json.items.find(u => u.email === 'viewer@alnoor.example');
const va = (await R.get('/api/tenancy/access/' + viewer.id)).json;
log('viewer access seen by branch admin', JSON.stringify({ canEdit: va.canEdit, reason: va.readOnlyReason, companies: va.companies, opts: va.options?.map(o => [o.code, o.canGiveAllBranches, o.branches.length]) }));
log('PUT tenant as branch-limited', (await R.put('/api/tenancy/tenant', { ...(await R.get('/api/tenancy/tenant')).json })).status);
console.log(JSON.stringify({ shjEmail, brEmail }));
