import fs from 'node:fs';
import { open, B, OUT, shot } from './common.mjs';
const log = []; const L = (...a) => { const s = a.join(' '); log.push(s); console.log(s); };
const lang = process.argv[2] || 'en';
const { browser, page, writes } = await open(lang === 'ar' ? 'admin.ar@alnoor.example' : 'admin@alnoor.example');
const reqs = []; page.on('request', r => { if (r.url().includes('/api/reports/')) reqs.push(r.url().replace(B, '')); });
await page.goto(B + '/reports/catalog'); await page.waitForTimeout(1500);
const names = lang === 'ar' ? { ubr: 'المستخدمون حسب الدور', rs: 'الأدوار والصلاحيات', show: 'عرض' } : { ubr: 'Users by role', rs: 'Roles and access', show: 'Show' };
await page.getByText(names.ubr, { exact: true }).first().click(); await page.waitForTimeout(800);
const lookup = page.locator('[data-field="role"] input');
await lookup.click(); await page.keyboard.type(lang === 'ar' ? 'مدير الشركة' : 'Company manager'); await page.waitForTimeout(1000);
await page.keyboard.press('ArrowDown'); await page.keyboard.press('Enter'); await page.waitForTimeout(300);
await page.getByRole('button', { name: names.show, exact: true }).click(); await page.waitForTimeout(2000);
L('users by role (company manager)', (await page.locator('.report-document, [class*=report]').last().innerText().catch(() => '')).replace(/\n/g, ' | ').slice(0, 1200));
await shot(page, `06-report-users-by-role-${lang}`);
await page.getByText(names.rs, { exact: true }).first().click(); await page.waitForTimeout(800);
await page.getByRole('button', { name: names.show, exact: true }).click(); await page.waitForTimeout(2000);
L('role summary', (await page.locator('.report-document, [class*=report]').last().innerText().catch(() => '')).replace(/\n/g, ' | ').slice(0, 1500));
L('group by select value', await page.locator('[data-field="groupBy"] select, select').evaluateAll(es => es.map(e => e.closest('[data-field]')?.getAttribute('data-field') + '=' + e.options[e.selectedIndex]?.text)));
await shot(page, `07-report-role-summary-${lang}`);
L('report requests', JSON.stringify(reqs));
fs.writeFileSync(`${OUT}/browser/explore-reports-${lang}.log`, log.join('\n'));
await browser.close();
