import { open, shot } from './pw.mjs';
const base = process.argv[2], out = process.argv[3];
const log = (...a) => console.log(...a);
const { browser, page } = await open(base, 'admin@alnoor.example', { width: 1600, height: 900 });
const active = () => page.evaluate(() => { const e = document.activeElement; return `${e?.tagName}${e?.getAttribute('role') ? '[' + e.getAttribute('role') + ']' : ''} ${(e?.getAttribute('aria-label') || e?.textContent || '').slice(0, 60).replace(/\s+/g, ' ')}`; });
const count = async () => (await page.locator('body').innerText()).match(/[\d,]+ users?\b/i)?.[0];
await page.getByRole('navigation').getByRole('link', { name: 'Users', exact: true }).first().click();
let t0 = Date.now();
await page.getByRole('row').nth(5).waitFor();
log('users list rendered in', Date.now() - t0, 'ms; count:', await count(), '; focus:', await active());
log('DOM rows:', await page.getByRole('row').count());
await shot(page, out + '/01-users-list-100k-en.jpg');
// quick search as you type, shortest name-derived text, row 17
t0 = Date.now();
await page.keyboard.type('m pi');
await page.waitForFunction(() => /1,651/.test(document.body.innerText), null, { timeout: 10000 }).catch(() => {});
log('typed "m pi" -> count', await count(), 'after', Date.now() - t0, 'ms');
const rows = await page.getByRole('row').allInnerTexts();
log('row index of target among rendered:', rows.findIndex(r => r.includes('Majid Anil Pillai')));
await shot(page, out + '/02-search-m-pi-target-visible.jpg');
// keyboard: clear, type prefixes, Enter opens best match
await page.keyboard.press('Control+a'); await page.keyboard.type('maj ani pil');
await page.waitForTimeout(1200);
await page.keyboard.press('Enter');
await page.waitForTimeout(1000);
log('after Enter: panel shows target:', (await page.locator('aside, [role="complementary"], [role="dialog"], form').allInnerTexts()).join(' ').includes('majid.pillai.068311'));
await shot(page, out + '/03-enter-opens-best-match.jpg');
await page.keyboard.press('Escape'); await page.waitForTimeout(400);
log('after Esc focus:', await active());
// grid navigation
await page.keyboard.press('Escape'); await page.waitForTimeout(300);
const sb = page.getByRole('searchbox').or(page.getByLabel(/search/i)).first();
await sb.fill(''); await page.waitForTimeout(800);
await sb.focus(); await page.keyboard.press('ArrowDown'); await page.waitForTimeout(200);
log('ArrowDown from search -> focus:', await active());
await page.keyboard.press('End'); await page.waitForTimeout(1500);
log('End -> focus:', await active());
await shot(page, out + '/04-end-of-100k-rows.jpg');
await page.keyboard.press('Home'); await page.waitForTimeout(800);
await page.keyboard.press('Space'); await page.keyboard.press('Shift+ArrowDown'); await page.keyboard.press('Shift+ArrowDown');
await page.waitForTimeout(300);
log('after Space + Shift+Down x2:', (await page.locator('body').innerText()).match(/\d+ (selected|chosen)[^\n]*/i)?.[0]);
await page.keyboard.press('Control+a'); await page.waitForTimeout(300); await page.keyboard.press('Control+a'); await page.waitForTimeout(500);
log('after Ctrl+A twice:', (await page.locator('body').innerText()).match(/All [\d,]+ [^\n]*/i)?.[0]);
await shot(page, out + '/05-all-matching-selected-bulk.jpg');
await page.keyboard.press('Escape');
// header sort by keyboard, column menu
const hdr = page.getByRole('columnheader', { name: /^E-mail/ }).first();
await hdr.focus(); await page.keyboard.press('Enter'); await page.waitForTimeout(1000);
log('sorted by e-mail, url:', page.url());
const menuBtn = page.getByRole('button', { name: /E-mail.*(menu|options|filter)|column menu/i }).first();
log('column menu buttons:', await page.getByRole('columnheader').locator('button').count());
await page.getByRole('columnheader', { name: /^Language/ }).locator('button').last().click().catch(e => log('lang menu click failed', e.message.slice(0, 80)));
await page.waitForTimeout(500);
log('menu items:', (await page.getByRole('menuitem').allInnerTexts()).join(' | '));
await shot(page, out + '/06-column-menu.jpg');
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Columns' }).click(); await page.waitForTimeout(500);
log('column chooser text:', (await page.locator('[role="dialog"], [role="menu"], .popover').first().innerText().catch(() => '')).replace(/\s+/g, ' ').slice(0, 200));
await page.keyboard.press('Escape');
await browser.close();
