import { createRequire } from "node:module";
const require = createRequire("/home/shan/critic/p02-tenancy-r8/gauntlet/compare/package.json");
const { chromium } = require("playwright-core");
const base = process.argv[2]; const out = "/home/shan/evidence-staging/p02-tenancy/r8";
const browser = await chromium.launch({ executablePath: "/home/shan/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome" });
const ctx = await browser.newContext({ viewport: { width: 1400, height: 900 } }); const page = await ctx.newPage();
await page.goto(base + "/"); await page.evaluate(() => { localStorage.clear(); localStorage.setItem("erp.language", "en"); }); await page.goto(base + "/");
await page.locator('input[name="email"]').waitFor();
await page.keyboard.type("admin@alnoor.example"); await page.keyboard.press("Tab"); await page.keyboard.type("Demo-Pass-2026"); await page.keyboard.press("Enter"); await page.waitForTimeout(2500);
await page.goto(base + "/tenancy/companies"); await page.waitForTimeout(2000);
await page.keyboard.press("Alt+n"); await page.waitForTimeout(800);
await page.keyboard.type("Falcon Keyboard Industries LLC"); await page.keyboard.press("Tab"); await page.keyboard.type("صناعات الصقر");
await page.keyboard.press("Control+s"); await page.waitForTimeout(2000);
const v = await page.evaluate(() => document.activeElement?.value); console.log("branch EN prefilled:", v);
await page.keyboard.press("Control+a"); await page.keyboard.type("Ajman plant");
await page.keyboard.press("Enter"); await page.waitForTimeout(2000);
const t = await page.evaluate(() => [...document.querySelectorAll("h2,h3")].map((h) => h.textContent).filter((x) => /Branch/.test(x)).join("|"));
console.log("after Enter:", t, "focus:", await page.evaluate(() => document.activeElement?.getAttribute("name")));
await page.screenshot({ path: `${out}/07-branch-added-enter-en.jpg`, type: "jpeg", quality: 70 });
await browser.close();
